#!/usr/bin/perl

use Cache::Memcached;

@vars = split(/&/, $ENV{'QUERY_STRING'});

for $v (@vars) {
	($key, $val) = split(/=/, $v, 2);
	$val =~ s/[^0-9]//g;
	$var{$key} = $val;
}

if ($ENV{'PATH_INFO'} =~ /^\/([0-9]+)\/([0-9]+)\/([0-9]+)/) {
	$var{'z'} = $1;
	$var{'x'} = $2;
	$var{'y'} = $3;
}

unless ($var{'z'} =~ /^[0-9]+$/ &&
        $var{'x'} =~ /^[0-9]+$/ &&
        $var{'y'} =~ /^[0-9]+$/) {
	print "Content-type: text/html\n\nUnrecognized tile specification\n";
	exit 0;
}

print "Content-type: image/png\n\n";

$cache = "/tmp/tile";
$cachefile = "$cache/$var{'z'}/$var{'x'}/$var{'y'}.png";

$memd = new Cache::Memcached {
	'servers' => [ "localhost:11211" ],
};

$cached = $memd->get($cachefile);
if ($cached) {
	print $cached;
	exit 0;
}

$data = "";
open(IN, "/srv/gps-tile.openstreetmap.org/datamaps/render -f /srv/gps-tile.openstreetmap.org/shapes/lines-directional.dm -t 0 -g -C 256 /srv/gps-tile.openstreetmap.org/shapes/current $var{'z'} $var{'x'} $var{'y'} | pngquant --speed 10 64 |");
while (<IN>) {
	$data .= $_;
}
close(IN);

$| = 1;
print $data;

$memd->set($cachefile, $data);
exit 0;
